### ISSUE TITLE
[BUG]: Different results in CEC2015 series of benchmark functions compared with the original Matlab implementation!

### ISSUE THREAD

**Issue by JixiangChen-Jimmy** [thieu1995/opfunu#10]
### Description of the bug

Hi, I was benchmarking results on CEC2015 problems. The implementation of the methods I selected is via Matlab and python. For python codes, I followed your implementation of CEC2015. For Matlab codes, I followed the zip file provided by the competition authors (https://github.com/P-N-Suganthan/CEC2015), and when I compared optimization results of the selected methods, I found that on some CEC2015 problems, these two implementations returned different results.
I am looking forward to the bug fixation!

### Steps To Reproduce

Here are the ones with problems: F4, F6, F7, F11, F12, F13, F14, and F15. Among them, some result in minor differences, like 1~2. Even so, it does influence the comparison. Others (e.g., F12) result in a huge gap in the order of magnitudes.
Currently, I have not found the right way to fix this, but I do find mistakes in CEC2015 problems, such as on F12, the leveraged input file is mistaken from the ones of F10.

**Comment by thieu1995** [comment]
Hi @JixiangChen-Jimmy ,
I have some questions

1) Which algorithms are you using?
2) How do you ensure your algorithms in python and Matlab code are identical? 
3) Because Meta-Heuristic Algorithms are non-deterministic (randomized). So how do you ensure the results are the same when running on python only, not to mention when comparing Matlab and python code?

**Comment by JixiangChen-Jimmy** [comment]
HI @thieu1995, thanks for the reply. In recent days, I have located the origin of the difference, which does not come from your code. 
I was conducting experiments on different Meta-heuristic methods implemented in different coding languages, i.e., Matlab and python. For Matlab methods, I implemented the official CEC15 expensive optimization API from https://github.com/P-N-Suganthan/CEC2015. For python methods, I implemented API from your repository. I checked the results by inputting the same x and checking whether the output function evaluation results are identical. 
I confirmed your implementation of these functions, which is identical to the formulas in the paper 'Problem Definitions and Evaluation Criteria for CEC 2015 Special Session on Bound Constrained Single-Objective Computationally Expensive Numerical Optimization'. But there are mistakes in F12 I mentioned above, where you mistook the input file of F10 (shift, rotate).
While the problem lies in that the official implementation of functions is not strictly identical to the formulas. I provided a more detailed description here: https://github.com/P-N-Suganthan/CEC2015/issues/1
I think this should be noticed by researchers when they try to compare different methods in different languages and leverage different APIs.

**Comment by thieu1995** [comment]
Thank @JixiangChen-Jimmy ,

However, You should know that we can't compare the problem on different languages unless you use the same methods in the same environments. For example, You implement the PSO algorithm in Python. You use my Python code API for CEC functions in python code. And you also use oct2py (library) to map the Matlab code CEC function to the Python environment. Then you can compare those results. 
For example, you can check this repo if you want to do it. (https://github.com/thieu1995/cec2011-real-world).

You can't compare results from PSO in Python versus PSO in Matlab. They can never compare to each other (You can not trust the results of those comparisons). Thanks for your effort anyway. I will fix the mistake soon. Now I am busy with other work. 

I've read your comments on the Suganthan repository. I don't think he cares as anyone else. They now mostly use CEC2021, CEC2020, and CEC2019 to compare in the papers. However, when implementing all the CEC competitions, I found many mistakes in their papers. But that competition they move fast. It is like no one cared. I'm not sure.

**Comment by JixiangChen-Jimmy** [comment]
Hi @thieu1995 , thanks for your reply and the effort in maintaining the code implementation. I have some questions about 'You can't compare results from PSO in Python versus PSO in Matlab. They can never compare to each other (You can not trust the results of those comparisons).' Is this because of the difference in exploited packages of algorithm implementation in different languages? Could you provide a more detailed explanation of the reason or some reference for me to learn about this issue?

**Comment by thieu1995** [comment]
@JixiangChen-Jimmy ,

Yeah, when implementing PSO in Python, you use different package such as numpy, and different functions in numpy. For example, random related functions. 
Also for Matlab code, you use random related functions. You don't know these functions can give the same results or not. 
For example, rand() function in Matlab give different results with rand() function in Numpy.

**Comment by JixiangChen-Jimmy** [comment]
@thieu1995 Thanks for the explanation. I think many metaheuristic methods include random parts to different extents. That's an important motivation to conduct independent and repeated runs of experiments for a single method on one benchmark problem to indicate its performance reasonably. I am not pursuing identical results for one method implemented in different languages, but I am trying to compare different methods. Despite they are implemented in different languages and have potential differences in exploited packages, I keep the benchmark problems identical and conduct independent runs of experiments on these methods. I think this is a fair comparison of the performance of different methods. Do you have any suggestions?

**Comment by thieu1995** [comment]
@JixiangChen-Jimmy 
Let's be clear on this. There are two problems. 
1st: Same benchmark functions from different languages. This is the reason you created this issue in the first place. Even the benchmark functions don't have random components, and you have to ensure they are identical in the code between Matlab and Python. Are you sure they are identical? (My code and the code in the Suganthan repository)

2nd: Same benchmark functions from different languages. As I explain in the previous reply, you can't compare them because the Meta-Heuristic Algorithm is an approximation (random-based).

3rd: Different benchmark functions from different languages. This is okay. However, you have to make sure the 1st. Then you can call it a fair comparison. I know there are several good algorithms in Matlab code but not in Python code. You want to compare them. I suggest using the benchmark functions from Matlab code. For example, you take the Matlab code from  Suganthan and use oct2py (library) to map that Matlab code to run on a python environment. Then you can use algorithms in Python to run that Matlab code. Check out my repo; you can do it with other CEC functions.

**Comment by JixiangChen-Jimmy** [comment]
@thieu1995 Yeah, it is clear now. Thank you for the explanation. I have revised your code to make them identical to that in Suganthan repository and checked the results by inputting the same _x_ and making sure the obtained function evaluations _y_ are identical.
